const commonStoreItemStructure = {
  KeySchema: [
    { AttributeName: 'StoreIdentifier', KeyType: 'HASH' },
    { AttributeName: 'LocalItemCode', KeyType: 'RANGE' },
  ],
  AttributeDefinitions: [
    { AttributeName: 'StoreIdentifier', AttributeType: 'S' },
    { AttributeName: 'LocalItemCode', AttributeType: 'S' },
  ],
  ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
};

const tableDefinitions = {
    promotion: {
      KeySchema: [
        { AttributeName: 'StoreIdentifier', KeyType: 'HASH' },
        { AttributeName: 'PromotionItemLineKey', KeyType: 'RANGE' },
      ],
      AttributeDefinitions: [
        { AttributeName: 'StoreIdentifier', AttributeType: 'S' },
        { AttributeName: 'PromotionItemLineKey', AttributeType: 'S' },
      ],
      ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
    },
    'promotion-metadata': {
      KeySchema: [
        { AttributeName: 'PromotionCode', KeyType: 'HASH' },
        { AttributeName: 'DigitalContentKey', KeyType: 'RANGE' },
      ],
      AttributeDefinitions: [
        { AttributeName: 'PromotionCode', AttributeType: 'S' },
        { AttributeName: 'DigitalContentKey', AttributeType: 'S' },
      ],
      ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
    },
    'exchange-rate': {
      KeySchema: [
        { AttributeName: 'Currencies', KeyType: 'HASH' },
        { AttributeName: 'Timestamp', KeyType: 'RANGE' },
      ],
      AttributeDefinitions: [
        { AttributeName: 'Currencies', AttributeType: 'S' },
        { AttributeName: 'Timestamp', AttributeType: 'N' },
      ],
      ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
    },
    'dcis-product-categories': {
      KeySchema: [{ AttributeName: 'code', KeyType: 'HASH' }],
      AttributeDefinitions: [{ AttributeName: 'code', AttributeType: 'S' }],
      ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
    },
    barcode: {
      KeySchema: [
        { AttributeName: 'BarCode', KeyType: 'HASH' },
        { AttributeName: 'SapCodes', KeyType: 'RANGE' },
      ],
      AttributeDefinitions: [
        { AttributeName: 'BarCode', AttributeType: 'S' },
        { AttributeName: 'SapCodes', AttributeType: 'S' },
      ],
      ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
    },
    stocks: commonStoreItemStructure,
    'stock-delta': commonStoreItemStructure,
    'retail-price-aggregate': commonStoreItemStructure,
    'retail-price': commonStoreItemStructure,
    'retail-price-v2': commonStoreItemStructure,
  };
  
onst tableData = {
    promotion: [
        {
            StoreIdentifier: 'STORE_1',
            PromotionItemLineKey: 'KEY_1',
            PromotionStartDate: 20210625,
            PromotionPrice: -1,
            LocalItemDescription: 'Mb.Bp  M Resin Bp',
            CampaignName: 'Liquidation (Delisted)',
            PercentOff: 20,
            CompanyCode: 'MO01',
            CampaignType: 'Liquidation',
            DiscountUnit: 1,
            LocalItemCategory: '50',
            Currency: 'HKD',
            GlobalItemDescription: 'Mb.Bp  M Resin Bp',
            LocalItemCode: '2409998',
            ExportTimestamp: 20220203093931,
            PromotionType: 4,
            LayerNumber: '-1',
            PromotionTypeDescription: 'Liquidation Promotion',
            CustomerTypes: 'Dufry Red (Platinum),Dufry Red (Gold),Dufry Red (Silver)',
            DiscountValue: 20,
            PriceType: 'NA',
            ConditionValue: -1,
            PromotionEndDate: 20220821,
            GlobalItemCode: '2409998',
            GlobalStoreDescription: 'Temptation, Parisian Macau (MODB)',
            PromotionStatus: '1',
            DiscountMessage: 'NA',
            DiscountType: 1,
            CampaignID: 36,
            ConditionType: 0,
            PromotionCode: 'ADVPR2021022298',
            RewardItem: 0,
            PromotionDescription: 'Save 20.00%',
            GlobalStoreCode: 'MO01CHN0050021',
            MultibuyFlag: '0',
          },
          {
            StoreIdentifier: 'STORE_1',
            PromotionItemLineKey: 'KEY_2',
            PromotionStartDate: 20210625,
            PromotionPrice: -1,
            LocalItemDescription: 'Mb.Bp  M Resin Bp',
            CampaignName: 'Liquidation (Delisted)',
            PercentOff: 20,
            CompanyCode: 'MO01',
            CampaignType: 'Liquidation',
            DiscountUnit: 1,
            LocalItemCategory: '50',
            Currency: 'HKD',
            GlobalItemDescription: 'Mb.Bp  M Resin Bp',
            LocalItemCode: '2409998',
            ExportTimestamp: 20220203093921,
            PromotionType: 4,
            LayerNumber: '-1',
            PromotionTypeDescription: 'Liquidation Promotion',
            CustomerTypes: 'Dufry Red (Platinum),Dufry Red (Gold),Dufry Red (Silver)',
            DiscountValue: 20,
            PriceType: 'NA',
            ConditionValue: -1,
            PromotionEndDate: 20220821,
            GlobalItemCode: '2409998',
            GlobalStoreDescription: 'Temptation, Parisian Macau (MODB)',
            PromotionStatus: '1',
            DiscountMessage: 'NA',
            DiscountType: 1,
            CampaignID: 36,
            ConditionType: 0,
            PromotionCode: 'ADVPR2021022298',
            RewardItem: 0,
            PromotionDescription: 'Save 20.00%',
            GlobalStoreCode: 'MO01CHN0050021',
            MultibuyFlag: '0',
          },
    ],
    'promotion-metadata': [
        {
            ModifiedDate: '30.05.2019 11:00:36',
            DigitalContentDescription: 'NA',
            Language: 'English',
            MediaType: 'Picture',
            Url: 'https://images.shopdutyfree.com/image/upload/v1544790372/media/amlabel/Save_35por.png',
            ModifiedBy: '1478095812173',
            Title: 'Save_35por',
            CreatedDate: '30.05.2019 11:00:36',
            DigitalContentKey: 'KEY1',
            PromotionCode: 'CODE1',
            CreatedBy: '1478095812173',
            MediaCategory: 'PICTURE',
            ExportTimestamp: 20200319120020,
          },
          {
            ModifiedDate: '30.05.2019 11:00:36',
            DigitalContentDescription: 'NA',
            Language: 'English',
            MediaType: 'Picture',
            Url: 'https://images.shopdutyfree.com/image/upload/v1544790372/media/amlabel/Save_35por.png',
            ModifiedBy: '1478095812173',
            Title: 'Save_35por',
            CreatedDate: '30.05.2019 11:00:36',
            DigitalContentKey: 'KEY2',
            PromotionCode: 'CODE1',
            CreatedBy: '1478095812173',
            MediaCategory: 'PICTURE',
            ExportTimestamp: 20200319120010,
          },
    ],
    'exchange-rate': [
        {
            Timestamp: 1654819200,
            Currencies: 'EURUSD',
            'ConversionRate ': 1.08144088,
          },
          {
            Timestamp: 1654818200,
            Currencies: 'EURUSD',
            'ConversionRate ': 1.08133088,
          },
          {
            Timestamp: 1654817200,
            Currencies: 'EURUSD',
            'ConversionRate ': 1.08122088,
          },
    ],
    'dcis-product-categories': [
        {
            code: 'DCIS_999999',
            parent: 'DCIS',
            labels: {
              de_DE: 'Tobacco',
              el_GR: '',
              en_AU: 'Tobacco',
              en_GB: 'Tobacco',
              en_US: 'Tobacco',
              es_ES: 'Tabaco',
              fi_FI: 'Tupakka',
              fr_FR: 'Tabac',
              it_IT: 'Tabacchi',
              ja_JP: '',
              ko_KR: '담배',
              pt_BR: 'Tabaco',
              pt_PT: 'Tabaco',
              ru_RU: 'Табак',
              sv_SE: 'Tobak',
              zh_CN: '烟草',
              zh_HK: '煙草',
            },
            timeToLive: 1727877185,
          },
    ],
    barcode: [
        {
            SapCodes: ' 2784993008',
            BarCode: '5045116822448',
          },
    ],
    stocks: [
        {
            StockAvailableQuantity: 2,
            HfmStoreCode: '6002_05',
            StockQuantity: 2,
            GlobalItemDesc: 'EL Pleasures EDP 100ml',
            GlobalItemCode: '1001755',
            ExpiryDate: 1749112307,
            StockDate: 20250504,
            CompanyCode: 'DPE',
            StockReservedQuantity: 0,
            HfmCompanyCode: '6002',
            GlobalStoreDesc: 'EWR Newark Concourse 2 (USNG)',
            LocalItemCode: '1001755',
            StoreIdentifier: 'DPEUSNG',
            ExportTimestamp: 20250505083150,
            GlobalStoreCode: 'DPEUSA0030015',
            StockType: 'F',
          },
          {
            StockAvailableQuantity: 2,
            HfmStoreCode: '6002_05',
            StockQuantity: 2,
            GlobalItemDesc: 'EL Pleasures EDP 100ml',
            GlobalItemCode: '1001750',
            ExpiryDate: 1749112307,
            StockDate: 20250504,
            CompanyCode: 'DPE',
            StockReservedQuantity: 0,
            HfmCompanyCode: '6002',
            GlobalStoreDesc: 'EWR Newark Concourse 2 (USNG)',
            LocalItemCode: '1001750',
            StoreIdentifier: 'DPEUSNG',
            ExportTimestamp: 20250505083140,
            GlobalStoreCode: 'DPEUSA0030015',
            StockType: 'I',
          },
    ],
    'stock-delta': [
        {
            StockAvailableQuantity: 2,
            HfmStoreCode: '6002_05',
            StockQuantity: 2,
            GlobalItemDesc: 'Talisker 10YO 45.8% 100CL',
            GlobalItemCode: '1000019',
            ExpiryDate: 1749112307,
            StockDate: 20250504,
            CompanyCode: 'DPE',
            StockReservedQuantity: 0,
            HfmCompanyCode: '6002',
            GlobalStoreDesc: 'EWR Newark Concourse 2 (USNG)',
            LocalItemCode: '1000019',
            StoreIdentifier: 'DPEUSNG',
            ExportTimestamp: 20250505083150,
            GlobalStoreCode: 'DPEUSA0030015',
            StockType: 'F',
          },
          {
            StockAvailableQuantity: 2,
            HfmStoreCode: '6002_05',
            StockQuantity: 2,
            GlobalItemDesc: 'R Martin VSOP 40% 100cl',
            GlobalItemCode: '1000140',
            ExpiryDate: 1749112307,
            StockDate: 20250504,
            CompanyCode: 'DPE',
            StockReservedQuantity: 0,
            HfmCompanyCode: '6002',
            GlobalStoreDesc: 'EWR Newark Concourse 2 (USNG)',
            LocalItemCode: '1000140',
            StoreIdentifier: 'DPEUSNG',
            ExportTimestamp: 20250505083140,
            GlobalStoreCode: 'DPEUSA0030015',
            StockType: 'I',
          },
    ],
    'retail-price-aggregate': [
        {
            StoreIdentifier: 'AU01AUPB',
            LocalItemCode: '1000002',
            Active: true,
            CompetitorDescription: 'NA',
            CompetitorPrice: -1,
            CurrencyDF: 'AUD',
            CurrencyDP: 'AUD',
            ExpiryDate: 0,
            ExportTimestamp: 20220608115530,
            GlobalItemCode: '1000002',
            GlobalItemDescription: 'Glenfiddich 15YO D.E 51% 100CL',
            GlobalStoreCode: 'AU01AUL0040016',
            HfmStoreCode: '8001_123',
            IsNovelty: false,
            IsTravelExclusive: true,
            ItemRank: -1,
            LocalItemDescription: 'Glenfiddich 15YO D.E 51% 100CL',
            RetailPriceDF: 123,
            RetailPriceDP: 108,
          },
    ],
    'retail-price': [
        {
            HfmStoreCode: '8001_123',
            ExpiryDate: 0,
            CompetitorDescription: 'NA',
            GlobalStoreCode: 'AU01AUL0040016',
            StoreIdentifier: 'AU01AUPB',
            IsTravelExclusive: 'True',
            RetailPriceDF: 123,
            ExportTimestamp: 20230808115530,
            CompetitorPrice: -1,
            CurrencyDF: 'AUD',
            GlobalItemDescription: 'Glenfiddich 15YO D.E 51% 100CL',
            Active: 'False',
            GlobalItemCode: '1000003',
            RetailPriceDP: 108,
            ItemRank: -1,
            LocalItemCode: '1000003',
            LocalItemDescription: 'Glenfiddich 15YO D.E 51% 100CL',
            IsNovelty: 'False',
            CurrencyDP: 'AUD',
          },
          {
            HfmStoreCode: '8001_123',
            ExpiryDate: 0,
            CompetitorDescription: 'NA',
            GlobalStoreCode: 'AU01AUL0040016',
            StoreIdentifier: 'AU01AUPB',
            IsTravelExclusive: 'True',
            RetailPriceDF: 123,
            ExportTimestamp: 20240808115530,
            CompetitorPrice: -1,
            CurrencyDF: 'AUD',
            GlobalItemDescription: 'Glenfiddich 15YO D.E 51% 100CL',
            Active: 'False',
            GlobalItemCode: '1000002',
            RetailPriceDP: 108,
            ItemRank: -1,
            LocalItemCode: '1000002',
            LocalItemDescription: 'Glenfiddich 15YO D.E 51% 100CL',
            IsNovelty: 'False',
            CurrencyDP: 'AUD',
          },
    ],
    'retail-price-v2': [
        {
            GlobalStoreCode: 'AU01AUL0040016',
            StoreIdentifier: 'AU01AUPB',
            ExportTimestamp: 20230808115530,
            CurrencyDF: 'AUD',
            RetailPriceDP: 108,
            LocalItemCode: '1000003',
            CurrencyDP: 'AUD',
            ExpiryDate: 0,
            RetailPriceDF: 0,
            PriceDateDF: '123',
            PriceDateDP: '123',
            PriceUomDF: '123',
            PriceUomDP: '123',
            Active: false,
          },
          {
            GlobalStoreCode: 'AU01AUL0040016',
            StoreIdentifier: 'AU01AUPB',
            ExportTimestamp: 20230808115530,
            CurrencyDF: 'AUD',
            RetailPriceDP: 108,
            LocalItemCode: '1000002',
            CurrencyDP: 'AUD',
            ExpiryDate: 0,
            RetailPriceDF: 0,
            PriceDateDF: '123',
            PriceDateDP: '123',
            PriceUomDF: '123',
            PriceUomDP: '123',
            Active: false,
          },
    ],
  };
  
  module.exports = { tableDefinitions, tableData };
